-- this is the process of starting a database that this program can interact with
--
--     Enter Username: sys as sysdba
--     Enter Password:
--
--     ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
--     CREATE USER INTERNALLOGIN IDENTIFIED BY INTERNALLOGIN1234;
--     GRANT DBA TO INTERNALLOGIN;
--     QUIT
--
--     TERMINAL: SQL-PLUS
--
--     Enter Username: INTERNALLOGIN
--     Enter Password: INTERNALLOGIN1234
--
-- Connected to:
-- Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production
-- Version 21.3.0.0.0
--
-- CREATE TABLE PRODUCT (
-- ID NUMBER(10) PRIMARY KEY,
-- NAME NVARCHAR2(20),
-- BRAND NVARCHAR2(20),
-- COUNT NUMBER(20),
-- PRICE NUMBER(20)
-- );
-- CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1;